<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Patrones\2_FactoryMethod\**" />
    <Compile Remove="Patrones\3_AbstractFactory\**" />
    <Compile Remove="Patrones\4_Bridge\**" />
    <Compile Remove="Patrones\5_Adapter\**" />
    <EmbeddedResource Remove="Patrones\2_FactoryMethod\**" />
    <EmbeddedResource Remove="Patrones\3_AbstractFactory\**" />
    <EmbeddedResource Remove="Patrones\4_Bridge\**" />
    <EmbeddedResource Remove="Patrones\5_Adapter\**" />
    <None Remove="Patrones\2_FactoryMethod\**" />
    <None Remove="Patrones\3_AbstractFactory\**" />
    <None Remove="Patrones\4_Bridge\**" />
    <None Remove="Patrones\5_Adapter\**" />
  </ItemGroup>

</Project>
